name: build
on:
  push:
    branches:
      - main
      - develop
  pull_request:
env:
  version_in_development: v0.0.1

jobs:
  draft-release:
    name: Draft Release if develop branch
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.draft_release.outputs.upload_url }}  
      release_id: ${{ steps.draft_release.outputs.id }}  
    steps:
      - name: Create Release
        id: draft_release
        if: github.ref == 'refs/heads/develop' || github.head_ref == 'feature/fix-toolchain-use'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          owner: tipi-build 
          repo: goldilock
          commitish: ${{ github.sha }}
          tag_name: ${{ env.version_in_development }}
          release_name: ${{ env.version_in_development }} ${{ github.sha }}
          draft: true
          prerelease: true 

  build-macos:
    name: build-macos
    runs-on: macos-latest
    needs: draft-release
    steps:
      - uses: actions/checkout@v2
      - name: install and build 
        run: |
          cmake -S . -B build/macos -DCMAKE_TOOLCHAIN_FILE=environments/host-cxx17.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build build/macos
          zip -j goldilock-macos.zip ./build/macos/src/goldilock
      - uses: actions/upload-artifact@v3
        with:
          name: goldilock_macos_artifact
          path: ./goldilock-macos.zip
      - name: Upload goldilock package
        if: ${{needs.draft-release.outputs.upload_url}}
        id: upload-tipi-goldilock-package 
        uses: actions/upload-release-asset@v1
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.draft-release.outputs.upload_url}}
          asset_path: ./goldilock-macos.zip
          asset_name: goldilock-macos.zip
          asset_content_type: application/zip

  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      env:
        TIPI_HOME_DIR: /usr/local/share/.tipi
    needs: draft-release
    steps:
      - name: setup docker
        run: |
          apt-get update
          apt-get install -y docker.io zip
      - uses: actions/checkout@v2
      - name: install and build 
        run: |
            docker pull tipibuild/tipi-ubuntu-1604:v0.0.65
            docker run --name tipi1604 \
            --volume ${{ github.workspace }}:${{ github.workspace }} \
            --env TIPI_ACCESS_TOKEN \
            --env TIPI_REFRESH_TOKEN \
            --env TIPI_VAULT_PASSPHRASE \
            --env TIPI_DISTRO_MODE=all \
            --env TIPI_POWWOW \
            --env TIPI_CACHE_FORCE_ENABLE \
            --env TIPI_CACHE_CONSUME_ONLY \
            --user $(id -u):$(id -g) \
            --detach \
            --workdir ${{ github.workspace }} \
            tipibuild/tipi-ubuntu-1604:v0.0.65 \
            sleep infinity
            docker exec --user $(id -u):$(id -g) tipi1604 /bin/bash -c "tipi run cmake -S . -B build/linux -DCMAKE_TOOLCHAIN_FILE=environments/host-cxx17-linux-static.cmake -DCMAKE_BUILD_TYPE=Release"
            docker exec --user $(id -u):$(id -g) tipi1604 /bin/bash -c "tipi run cmake --build build/linux"
            zip -j goldilock-linux.zip ./build/linux/src/goldilock
      - uses: actions/upload-artifact@v3
        with:
          name: goldilock_linux_artifact
          path: ./goldilock-linux.zip
      - name: Upload goldilock package
        if: ${{needs.draft-release.outputs.upload_url}}
        id: upload-tipi-goldilock-package 
        uses: actions/upload-release-asset@v1
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.draft-release.outputs.upload_url}}
          asset_path: ./goldilock-linux.zip
          asset_name: goldilock-linux.zip
          asset_content_type: application/zip